name: 'Chromatic'

# Event for the workflow
on: push

# List of jobs
jobs:
  chromatic-deployment:
    # Operating System
    runs-on: ubuntu-latest
    
    outputs: 
      deploy_url: ${{ steps.publish.outputs.buildUrl }}
    # Job steps
    steps:
      - uses: actions/checkout@v1
      - name: Install dependencies
        # ğŸ‘‡ Install dependencies with the same package manager used in the project (replace it as needed), e.g. yarn, npm, pnpm
        uses: pnpm/action-setup@v2.2.2
        with:
          # å¿…è¦ã«å¿œã˜ã¦ pnpm ã®ãƒãƒ¼ã‚¸ãƒ§ãƒ³ã‚’å¤‰æ›´ã—ã¦ãã ã•ã„
          version: 7.28.0
      - run: pnpm i --frozen-lockfile
        # ğŸ‘‡ Adds Chromatic as a step in the workflow
      - name: Publish to Chromatic
        id: publish
        uses: chromaui/action@v1
        # Chromatic GitHub Action options
        with:
          # ğŸ‘‡ Chromatic projectToken, refer to the manage page to obtain it.
          projectToken: ${{ secrets.CHROMATIC_PROJECT_TOKEN }}
          exitOnceUploaded: true