name: 'Chromatic'

# Event for the workflow
on: push

# List of jobs
jobs:
  chromatic-deployment:
    # Operating System
    runs-on: ubuntu-latest
    
    # Job steps
    steps:
      - uses: actions/checkout@v1
      - name: Install dependencies
        # ğŸ‘‡ Install dependencies with the same package manager used in the project (replace it as needed), e.g. yarn, npm, pnpm
        uses: pnpm/action-setup@v2.2.2
        with:
          # å¿…è¦ã«å¿œã˜ã¦ pnpm ã®ãƒãƒ¼ã‚¸ãƒ§ãƒ³ã‚’å¤‰æ›´ã—ã¦ãã ã•ã„
          version: 7.28.0
      - run: pnpm i --frozen-lockfile
        # ğŸ‘‡ Adds Chromatic as a step in the workflow
      - id: react
        environment:
          name: Publish to Chromatic react
          url: ${{ steps.react.outputs.buildUrl }}
        uses: chromaui/action@v1
        # Chromatic GitHub Action options
        with:
          # ğŸ‘‡ Chromatic projectToken, refer to the manage page to obtain it.
          projectToken: ${{ secrets.CHROMATIC_PROJECT_TOKEN }}
          exitOnceUploaded: true
          buildScriptName: "build-storybook-react"
      
      - id: vue
        environment:
          name: Publish to Chromatic vue
          url: ${{ steps.vue.outputs.buildUrl }}
        uses: chromaui/action@v1
        # Chromatic GitHub Action options
        with:
          # ğŸ‘‡ Chromatic projectToken, refer to the manage page to obtain it.
          projectToken: ${{ secrets.CHROMATIC_PROJECT_TOKEN }}
          exitOnceUploaded: true
          buildScriptName: "build-storybook-vue"
      
      - id: svelte
        environment:
          name: Publish to Chromatic svelte
          url: ${{ steps.svelte.outputs.buildUrl }}
        uses: chromaui/action@v1
        # Chromatic GitHub Action options
        with:
          # ğŸ‘‡ Chromatic projectToken, refer to the manage page to obtain it.
          projectToken: ${{ secrets.CHROMATIC_PROJECT_TOKEN }}
          exitOnceUploaded: true
          buildScriptName: "build-storybook-svelte"
      
      - id: preact
        environment:
          name: Publish to Chromatic preact
          url: ${{ steps.preact.outputs.buildUrl }}
        uses: chromaui/action@v1
        # Chromatic GitHub Action options
        with:
          # ğŸ‘‡ Chromatic projectToken, refer to the manage page to obtain it.
          projectToken: ${{ secrets.CHROMATIC_PROJECT_TOKEN }}
          exitOnceUploaded: true
          buildScriptName: "build-storybook-preact"
      
      - id: solid
        environment:
          name: Publish to Chromatic solid
          url: ${{ steps.solid.outputs.buildUrl }}
        uses: chromaui/action@v1
        # Chromatic GitHub Action options
        with:
          # ğŸ‘‡ Chromatic projectToken, refer to the manage page to obtain it.
          projectToken: ${{ secrets.CHROMATIC_PROJECT_TOKEN }}
          exitOnceUploaded: true
          buildScriptName: "build-storybook-solid"